image: php:7.4-cli
stages:
  - test
.job_template: &build_template
  before_script:
    - apt-get update && apt-get install -y git zip unzip
    - curl -sS https://getcomposer.org/installer | php
    - php composer.phar install
    - php composer.phar dumpautoload
test:unit:
  <<: *build_template
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - php composer.phar phpunit
test:static_analyze:
  <<: *build_template
  stage: test
  script:
    - cd $CI_PROJECT_DIR
    - php composer.phar static_analyze
