image: php:7.4-cli

before_script:
  - ls -la
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && mv composer.phar /usr/local/bin/composer \
    && chmod +x /usr/local/bin/composer
stages:
  - build
  - test
test:unit:
  stage: test
  variables:
    COMPOSER_ARGS: "--prefer-dist --ignore-platform-reqs --quiet --no-interaction --no-progress"
  script:
    - export $PHP_EXEC_ENV
    - cd $CI_PROJECT_DIR
    - php $PHP_ARGS composer.phar global config platform.php 7.3.19
    - php $PHP_ARGS composer.phar global require hirak/prestissimo --verbose
    - php $PHP_ARGS composer.phar install $COMPOSER_ARGS
    - cd $CI_PROJECT_DIR
    - php composer.phar test
